language: ruby
sudo: false
rvm:
  - 2.5.0
script:
  - cd spec/dummy  && RAILS_ENV=test bundle exec rake db:create db:migrate
  - cd ../..  && bundle exec rspec spec
before_install:
  - sudo apt-get update && sudo apt-get install -y $(grep -v '^\s*$' ./Aptfile | tr "\n" " ")
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- curl --silent --show-error --location --fail --retry 3 --output /tmp/google-chrome-stable_current_amd64.deb dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && (sudo dpkg -i /tmp/google-chrome-stable_current_amd64.deb || sudo apt-get -fy install) && rm -rf /tmp/google-chrome-stable_current_amd64.deb && /opt/google/chrome/google-chrome --version
deploy:
  provider: rubygems
  api_key:
    secure: PEMMDcT4SKPdv4xMJmIEpndOGePsV3kDOhUL0vEDjTeyxBrn+iBgHKF9itSYbUmOSTuOaiIVleYmuC6GoAmg4KcZIZvfCA61cGCX1ADU5nwh5FjC/tAEs8eShMR3RFG6wyykb4MdFkE2jVpm/W0pyciLgW2HrM6iYzI6X2iMn9E=
  gem: activeadmin_addons
  on:
    tags: true
    repo: platanus/activeadmin_addons
